"use client";

import { Syne } from "next/font/google";
import { Roboto_Mono } from "next/font/google";

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function CookiePolicyPage() {
  return (
    <section className="min-h-screen bg-[#fdfbf5] text-[#191919] px-6 py-15">
      <div className="">
        {/* TITLE */}
        <h1
          className={`${syne.className} text-6xl md:text-7xl font-semibold mb-20 text-center`}
        >
          Cookie Policy
        </h1>

        {/* META INFO */}
        <div className="space-y-4 mb-16">
          <p className="text-lg"></p>
          <p className="text-lg"></p>
        </div>

        {/* CONTENT */}
        <div
          className={` ${syne.className} space-y-10 text-2xl leading-relaxed  `}
        >
          <p>
            <span>Effective Date:</span> 03-Jun-2025
            <br />
            <br />
            <span>Last Updated:</span> 03-Jun-2025
            <br />
            <br />
            What are cookies? This Cookie Policy explains what cookies are and
            how we use them, the types of cookies we use i.e, the information we
            collect using cookies and how that information is used, and how to
            manage the cookie settings.
            <br />
            <br />
            Cookies are small text files that are used to store small pieces of
            information. They are stored on your device when the website is
            loaded on your browser. These cookies help us make the website
            function properly, make it more secure, provide better user
            experience, and understand how the website performs and to analyze
            what works and where it needs improvement.
            <br />
            <br />
            How do we use cookies? As most of the online services, our website
            uses first-party and third-party cookies for several purposes.
            First-party cookies are mostly necessary for the website to function
            the right way, and they do not collect any of your personally
            identifiable data.
            <br />
            <br />
            The third-party cookies used on our website are mainly for
            understanding how the website performs, how you interact with our
            website, keeping our services secure, providing advertisements that
            are relevant to you, and all in all providing you with a better and
            improved user experience and help speed up your future interactions
            with our website.
            <br />
            <br />
            Types of Cookies we use Manage cookie preferences Cookie Settings
            You can change your cookie preferences any time by clicking the
            above button. This will let you revisit the cookie consent banner
            and change your preferences or withdraw your consent right away.
            <br />
            <br />
            In addition to this, different browsers provide different methods to
            block and delete cookies used by websites. You can change the
            settings of your browser to block/delete the cookies. Listed below
            are the links to the support documents on how to manage and delete
            cookies from the major web browsers.
            <br />
            <br />
            <strong>Chrome:</strong>
            https://support.google.com/accounts/answer/32050
            <br />
            <br />
            <strong>Safari</strong>
            :https://support.apple.com/en-in/guide/safari/sfri11471/mac
            <br />
            <br />
            <strong>Firefox:</strong>
            https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectslug=delete-cookies-remove-info-websites-stored&redirectlocale=en-US
            <br />
            <br />
            <strong>Internet Explorer:</strong>
            https://support.microsoft.com/en-us/topic/how-to-delete-cookie-files-in-internet-explorer-bca9446f-d873-78de-77ba-d42645fa52fc
            <br />
            <br />
            If you are using any other web browser, please visit your browser’s
            official support documents.
            <br />
            <br />
            Cookie Policy Generated By CookieYes - Cookie Policy Generator.
          </p>
        </div>
      </div>
    </section>
  );
}
