import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Syne } from "next/font/google";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import PageTransition from "@/components/PageTransition";

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Variable.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});
const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Legacies Techno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#fdfbf5]">
      <body className="font-satoshi antialiased">
        <div
          className="
          border-[1.45px] border-[#191919] lg:m-4 bg-[#fdfbf5] 
          md:m-3
          m-3

          lg:px-12

          px-6
          overflow-x-hidden
     

          
         
        
        "
        >
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
